# _config.yml
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# If you keep pages under _pages/, be sure to include it:
include:
  - _pages
